  on:
    workflow_call:
      secrets:
        GCP_SA_KEY:
          required: true
  jobs:
    deploy:
      runs-on: ubuntu-latest
      permissions: read-all

      steps:
        - name: checkout
          uses: action/checkout@v4

        - name: Set up terraform
          uses: hashicorp/setup-terraform@v1
        - name: Init Terraform
          run:
           cd terraform
           | terraform init
          with:
            GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
        - name: Plan terraform
          run:
            cd terraform
            | terraform plan
          env:
            GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
        - name: deploy
          run:
            cd terraform |
            terraform apply -auto-approve
          with:
            GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}