on:
  workflow_call:


jobs:
    deploy:
      runs-on:  ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: hashicorp/setup-terraform@v1
        - id: "auth"
          uses: "google-github-actions/auth@v1"
          with:
            credentials_json: "${{ secrets.GCP_SA_KEY }}"

        - name: "Set up Cloud SDK"
          uses: "google-github-actions/setup-gcloud@v1"

        - name: "Use gcloud CLI"
          run: "gcloud info"
        - name: Init Terraform
          run:
            terraform init
          env:
            GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
        - name: format check
          run: terraform fmt -check

        - name: Plan terraform
          run:
            terraform plan
          env:
            GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
        - name: deploy
          run:
            terraform apply -auto-approve
          env:
            GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}