name: ci pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      - name: give permission to gradle
        run: chmod +x gradlew

      - name: build with gradle wrapper
        run: ./gradlew clean build

      - name: Authenticate with Google Cloud
        run: |
            echo ${{ secrets.GCP_SA_KEY }} | base64 --decode > /tmp/gcp-key.json
            gcloud auth activate-service-account --key-file=/tmp/gcp-key.json
            gcloud auth configure-docker

      - name: Build Docker image with Jib
        run: ./gradlew jib --image=gcr.io/${{ secrets.GCP_PROJECT_ID }}/cicd:latest

