name: ci pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@4
      - name: Set up JDK 17
        uses: actions/setup-java@4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      - name: build with gradle wrapper
        run: ./gradlew clean build

