name: ci pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      - name: give permission to gradle
        run: chmod +x gradlew

      - name: build with gradle wrapper
        run: ./gradlew clean build

      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
            credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: Build Docker image with Jib
        run: ./gradlew jib --image=asia-south1-docker.pkg.dev/cicd-420214/cicd/artifact-registry/cicd:latest bootJar -x test

      - name: deployment
        uses: ./.github/workflows/cd-pipeline
        with:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
